blank_issues_enabled: false
contact_links:
  - name: Support
    url: https://example.com/support
    about: If you have questions, visit our support page to get in touch with our team.

issue_templates:
  - name: Bug report
    description: Report a bug in the project
    labels: [bug]
  - name: Feature request
    description: Suggest a new feature or enhancement
    labels: [enhancement]
  - name: Form Bug Report
    description: Help us improve our documentation
    labels: [documentation]
